### ISSUE TITLE
new content required for 0.20.0

### ISSUE THREAD

**Issue by jennifer-shehane** [cypress-io/cypress-documentation#20]
@jennifer-shehane commented on [Tue Sep 05 2017](https://github.com/cypress-io/cypress-monorepo/issues/422)

- [x] Document how to call `cypress open` when locally installed vs globally installed. See https://github.com/cypress-io/cypress-monorepo/issues/415
- [x] Add `cypress open` debug flag to 'Debugging' doc
- [ ] Document Cypress.log https://github.com/cypress-io/cypress/issues/470
- [x] Cypress + cy both emit a ton of events which developers can use to tap into for extensibility. These need to be documented and use cases suggested https://github.com/cypress-io/cypress/issues/469
- [x] Document Cypress.Commands.overwrite https://github.com/cypress-io/cypress/issues/471
- [x] Include `assert` interface.
- [x] Document alert / confirm events. https://github.com/cypress-io/cypress/issues/621#issuecomment-327590318
