### ISSUE TITLE
Update react todo tutorial

### ISSUE THREAD

**Issue by avanslaars** [cypress-io/cypress-documentation#231]
- [x] Add numbers to the page links in the left nav
- [x] Add a release date column in the intro table
- [x] Add a Cypress version column to the intro table
