### ISSUE TITLE
Roadmap updates

### ISSUE THREAD

**Issue by amirrustam** [cypress-io/cypress-documentation#2491]
## I'm submitting a...

```
[ ] Bug report
[x] Content update
[ ] Process update (build, deployment, ... )
```

- [x] Mark cross browser support as complete
- [x] Mark mocha, Chai, Sinon upgrade as complete
- [x] Add new column to indicate what version an item released in
- [x] Add last updated tag at the top of the roadmap page
