### ISSUE TITLE
Waiting for promises with cy.wrap() examples and additional documentation

### ISSUE THREAD

**Issue by CypressCecelia** [cypress-io/cypress-documentation#2863]
## I'm submitting a...

```
[ ] Bug report
[X] Content update
[ ] Process update (build, deployment, ... )
```

## Context

There is existing documentation within cy.wrap() and in Cypress.Promise about using cy.wrap() to wait for a promise to resolve in order for it to be enqueued with other Cypress commands.

## Goal
We should improve the example and clarify, as well as identify other areas of the docs where this information should be added.

## References
https://docs.cypress.io/api/utilities/promise.html#Waiting-for-Promises
https://docs.cypress.io/api/commands/wrap.html#Syntax

## To-Do
- [ ] Write an example of a custom command that returns a Promise and using cy.wrap() to await that promise
- [ ] Add descriptive language that explains what is happening in the example
- [x] Identify areas in the documentation that need to have this example included
- [x] Decide on format, whether it will be its own section on different pages or as a Note that links back to an example on cy.wait or Cypress.Promise

**Comment by CypressHarry** [comment]
```javascript
it("access async return value", () => {
    // return promise that resolves to new value after 3 secs
    function resolveAfter3Second() {
      return new Promise((resolve) => {
        setTimeout(function () {
          resolve("delayed message");
        }, 3000);
      });
    }

    // async function awaits for resolved message
    async function generateDelayedMessage() {
      const message = await resolveAfter3Second();
      return message;
    }

    // wrap async function in cypress promise chain to pass value to command
    cy.wrap(generateDelayedMessage()).then((message) => {
        cy.log(message)
    });

  });
```
Example to use
